version: '3.8'

services:
  db:
    image: postgres:17
    volumes:
      - postgres_data_ninja2:/var/lib/postgresql/data/
    env_file:
      - ../.env
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    command: >
      sh -c "pip install -r requirements.txt &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
      - .env
    depends_on:
      - db

volumes:
  postgres_data_ninja2: 